# Generated by Django 6.0.3 on 2026-04-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='frequency',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
